### ISSUE TITLE
Your mod cannot run on my ADOFAI

### ISSUE THREAD

**Issue by punishzhang** [c3nb/JudgePracticeMod#1]
I downloaded judgepracticemod, I successfully loaded in the UUM, but if I open the game, it ALWAYS need restart, even if I do. ![image](https://user-images.githubusercontent.com/104713852/166138522-7d834c28-8db7-4c88-aa49-2ff979d54b17.png)

**Comment by c3nb** [comment]
I won't support that mod, you should use Overlayer instead that.
